# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnairequalitatif', '0002_author_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='users',
            field=models.ManyToManyField(to='questionnairequalitatif.Users'),
        ),
    ]
