# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnairequalitatif', '0003_auto_20170106_1144'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='users',
            new_name='user',
        ),
    ]
