# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnairequalitatif', '0004_auto_20170106_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='user', max_length=128),
            preserve_default=False,
        ),
    ]
