# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnairequalitatif', '0005_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='order',
            field=models.CharField(default='3', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
