# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnairequalitatif', '0006_auto_20170106_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=100, verbose_name="person's first name"),
        ),
    ]
