# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnairequalitatif', '0009_auto_20170106_1236'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Raison',
        ),
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
        migrations.AddField(
            model_name='author',
            name='raison',
            field=models.ManyToManyField(to='questionnairequalitatif.Raison', verbose_name='1. Pour quelles raisons avez-vous participé à cette activité ?'),
        ),
        migrations.AlterField(
            model_name='author',
            name='title',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non')], max_length=3),
        ),
    ]
