# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnairequalitatif', '0010_auto_20170106_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualitatif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lien', models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non')], max_length=3, verbose_name='2. Lors de cette activité d’agriculture urbaine, avez-vous rencontré ou tissé des liens avec une nouvelle personne?')),
                ('name', models.CharField(max_length=100, verbose_name="person's first name")),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('raison', models.ManyToManyField(to='questionnairequalitatif.Raison', verbose_name='1. Pour quelles raisons avez-vous participé à cette activité ?')),
            ],
        ),
        migrations.RemoveField(
            model_name='author',
            name='raison',
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='questionnairequalitatif.Qualitatif'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
