# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnairequalitatif', '0011_auto_20170106_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualitatif',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='qualitatif',
            name='name',
        ),
        migrations.AddField(
            model_name='qualitatif',
            name='age',
            field=models.CharField(choices=[('MOINS_18', 'Moins de 18 ans'), ('18_24', '18-24'), ('25_34', '25-34'), ('35_50', '35-50'), ('50_64', '50-64'), ('65_ET_PLUS', '65 et plus')], default='Sélectionnez', max_length=100, verbose_name='8. Votre âge :'),
        ),
        migrations.AddField(
            model_name='qualitatif',
            name='bien_etre',
            field=models.CharField(choices=[('PHYSIQUE', 'Physique? '), ('MENTAL', 'Mental?'), ('AUCUN', 'Ni l’un ni l’autre')], default='Sélectionnez', max_length=50, verbose_name='3. Considérez-vous que cette activité à contribué à votre bien-être?'),
        ),
        migrations.AddField(
            model_name='qualitatif',
            name='condition_physique_ou_cognitive',
            field=models.CharField(choices=[('OUI', 'Oui'), ('SI_OUI', 'Si oui, quoi?'), ('NON', 'Non')], default='Sélectionnez', max_length=100, verbose_name='10. Avez-vous une condition physique ou cognitive particulière?'),
        ),
        migrations.AddField(
            model_name='qualitatif',
            name='enfant_0_a_4',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default='0', max_length=1, verbose_name='9. Nombre d’enfants participants avec vous: - enfant(s) de 0-4 ans :'),
        ),
        migrations.AddField(
            model_name='qualitatif',
            name='enfant_13_a_17',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default='0', max_length=1, verbose_name='- enfant(s) de 13-17 ans :'),
        ),
        migrations.AddField(
            model_name='qualitatif',
            name='enfant_5_a_8',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default='0', max_length=1, verbose_name='- enfant(s) de 5-8 ans :'),
        ),
        migrations.AddField(
            model_name='qualitatif',
            name='enfant_8_a_12',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default='0', max_length=1, verbose_name='- enfant(s) de 8-12 ans :'),
        ),
        migrations.AddField(
            model_name='qualitatif',
            name='envie_legumes',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non')], default='Sélectionnez', max_length=3, verbose_name='4. Est-ce que cette activité vous a donné envie de manger plus de fruits/légumes?'),
        ),
        migrations.AddField(
            model_name='qualitatif',
            name='genre',
            field=models.CharField(choices=[('HOMME', 'Homme'), ('FEMME', 'Femme'), ('AUTRE', 'Autre')], default='Sélectionnez', max_length=100, verbose_name='7. Votre genre :'),
        ),
        migrations.AddField(
            model_name='qualitatif',
            name='implication',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non')], default='Sélectionnez', max_length=3, verbose_name='6. Suite à cette activité, vous sentez-vous plus impliqué dans votre quartier?'),
        ),
        migrations.AddField(
            model_name='qualitatif',
            name='langue',
            field=models.CharField(choices=[('FRANCAIS', 'Français'), ('ANGLAIS', 'Anglais'), ('AUTRE', 'Autre')], default='Sélectionnez', max_length=100, verbose_name='14. Quelle langue parlez vous le plus souvent à la maison?'),
        ),
        migrations.AddField(
            model_name='qualitatif',
            name='nouvelle_competence',
            field=models.CharField(choices=[('OUI', 'Oui'), ('SI_OUI', 'Si oui, quoi?'), ('NON', 'Non')], default='Sélectionnez', max_length=100, verbose_name='5. Avez-vous appris quelque chose de nouveau et/ou développé de nouvelles compétences suite à cette activité?'),
        ),
        migrations.AddField(
            model_name='qualitatif',
            name='quartier',
            field=models.CharField(choices=[('AHUNTSIC-CARTIERVILLE', 'Ahuntsic-Cartierville'), ('ANJOU', 'Anjou'), ('CÔTE-DES-NEIGES–NOTRE-DAME-DE-GRÂCE', 'Côte-des-Neiges–Notre-Dame-de-Grâce'), ('LACHINE', 'Lachine'), ('LASALLE', 'LaSalle'), ('LE PLATEAU-MONT-ROYAL', 'Le Plateau-Mont-Royal'), ('LE SUD-OUEST', 'Le Sud-Ouest'), ('L’ÎLE-BIZARD–SAINTE-GENEVIÈVE', 'L’Île-Bizard–Sainte-Geneviève'), ('MERCIER–HOCHELAGA-MAISONNEUVE', 'Mercier–Hochelaga-Maisonneuve'), ('MONTRÉAL-NORD', 'Montréal-Nord'), ('OUTREMONT', 'Outremont'), ('PIERREFONDS-ROXBORO', 'Pierrefonds-Roxboro'), ('RIVIÈRE-DES-PRAIRIES–POINTE-AUX-TREMBLES', 'Rivière-des-Prairies–Pointe-aux-Trembles'), ('ROSEMONT–LA PETITE-PATRIE', 'Rosemont–La Petite-Patrie'), ('SAINT-LAURENT', 'Saint-Laurent'), ('SAINT-LÉONARD', 'Saint-Léonard'), ('VERDUN', 'Verdun'), ('VILLE-MARIE', 'Ville-Marie'), ('VILLERAY–SAINT-MICHEL–PARC-EXTENSION', 'Villeray–Saint-Michel–Parc-Extension'), ('AUTRE', 'Autre')], default='Sélectionnez', max_length=1000, verbose_name='15. Quel est votre quartier de résidence?'),
        ),
        migrations.AddField(
            model_name='qualitatif',
            name='resident_depuis',
            field=models.CharField(choices=[('PAS_RESIDENT', 'Je ne suis pas Résident'), ('MOINS_1_ANS', "Moins d'un an"), ('ENTRE_1_ET_2_ANS', 'Entre 1 et 2 ans'), ('PLUS_DE_2_ANS', 'Plus de 2 ans')], default='Sélectionnez', max_length=100, verbose_name='17. Si vous n’êtes pas originaire de Montréal, depuis combien de temps vous y résidez?'),
        ),
        migrations.AddField(
            model_name='qualitatif',
            name='revenu_annuel_familial',
            field=models.CharField(choices=[('0_10K', '0 - 9 999$'), ('10K_20K', '10 000$ - 19 999$'), ('20K_30K', '20 000$ - 29 999$'), ('30K_40K', '30 000$ - 39 999$'), ('40K_50K', '40 000$ - 49 999$'), ('PLUS_DE_50K', 'Plus de 50 000$'), ('NE_REPOND_PAS', 'Je préfère ne pas répondre')], default='Sélectionnez', max_length=100, verbose_name='13. Quel est le revenu annuel familial avant impôt ?'),
        ),
        migrations.AddField(
            model_name='qualitatif',
            name='situation_familiale',
            field=models.CharField(choices=[('PERSONNE_SEULE', 'Personne seule'), ('COUPLE_SANS_ENFANT', 'Couple sans enfant'), ('COUPLE_AVEC_ENFANT', 'Couple avec enfant'), ('FAMILLE_MONO_PARENTALE', 'Famille mono-parentale')], default='Sélectionnez', max_length=100, verbose_name='11. Quelle est votre situation familiale ?'),
        ),
        migrations.AddField(
            model_name='qualitatif',
            name='source_revenus',
            field=models.CharField(choices=[('TRAVAIL', 'Travail'), ('ETUDE', 'Études'), ('PENSION', 'Pension'), ('ASSURANCE_EMPLOI', 'Assurance Emploi'), ('SECURITE_REVENU', 'Sécurité du revenu'), ('AUTRE', 'Autre')], default='Sélectionnez', max_length=100, verbose_name='12. Quelle est votre source principale de revenu?'),
        ),
        migrations.AddField(
            model_name='qualitatif',
            name='ville_origine',
            field=models.CharField(choices=[('AU_QUEBEC', 'Au Québec'), ('AILLEURS_AU_CANADA', 'Ailleurs au Canada'), ('AUTRE', 'Autre')], default='Sélectionnez', max_length=1000, verbose_name='16. Où se trouve votre ville d’origine?'),
        ),
        migrations.AlterField(
            model_name='qualitatif',
            name='lien',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non')], default='Sélectionnez', max_length=3, verbose_name='2. Lors de cette activité d’agriculture urbaine, avez-vous rencontré ou tissé des liens avec une nouvelle personne?'),
        ),
        migrations.AlterField(
            model_name='qualitatif',
            name='raison',
            field=models.ManyToManyField(default='Sélectionnez', to='questionnairequalitatif.Raison', verbose_name='1. Pour quelles raisons avez-vous participé à cette activité ?'),
        ),
    ]
