# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnairequalitatif', '0012_auto_20170106_1431'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.AlterField(
            model_name='qualitatif',
            name='bien_etre',
            field=models.CharField(choices=[('PHYSIQUE', 'Physique'), ('MENTAL', 'Mental'), ('AUCUN', 'Ni l’un ni l’autre')], default='Sélectionnez', max_length=50, verbose_name='3. Considérez-vous que cette activité à contribué à votre bien-être?'),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
