# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnairequalitatif', '0013_auto_20170106_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitatif',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name="Date d'envoi"),
        ),
    ]
