# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 22:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionnairequalitatif', '0014_qualitatif_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_organisme', models.TextField(blank=True)),
                ('nom_referent', models.TextField(blank=True)),
                ('courriel', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True)),
                ('mandat', models.TextField(blank=True)),
                ('objetif', models.TextField(blank=True)),
                ('personnes_impliquees', models.IntegerField(blank=True)),
                ('personnes_employees', models.IntegerField(blank=True)),
                ('personnes_moins_de_25', models.IntegerField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('signature', models.TextField(blank=True)),
                ('inscrit_newsletter', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
