# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnairequalitatif', '0015_profil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('order', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='profil',
            name='categories',
            field=models.ManyToManyField(to='questionnairequalitatif.Categories', verbose_name='8. Quelles sont les catégories d’activités mises sur pied par votre organisme?'),
        ),
    ]
