# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnairequalitatif', '0017_auto_20170106_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='order',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='profil',
            name='personnes_employees',
            field=models.IntegerField(blank=0),
        ),
        migrations.AlterField(
            model_name='profil',
            name='personnes_impliquees',
            field=models.IntegerField(blank=0),
        ),
        migrations.AlterField(
            model_name='profil',
            name='personnes_moins_de_25',
            field=models.IntegerField(blank=0),
        ),
    ]
