# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('questionnairequalitatif', '0018_auto_20170106_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='signature',
            new_name='adresse_jardin',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='avatar',
        ),
        migrations.AddField(
            model_name='profil',
            name='city',
            field=models.CharField(default='Montréal', max_length=255),
        ),
        migrations.AddField(
            model_name='profil',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='45.518519, -73.568063', max_length=63),
        ),
        migrations.AddField(
            model_name='profil',
            name='retombees',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='superficie',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='personnes_employees',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='personnes_impliquees',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='personnes_moins_de_25',
            field=models.IntegerField(blank=True),
        ),
    ]
