# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 23:02
from __future__ import unicode_literals

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('questionnairequalitatif', '0020_auto_20170106_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63),
        ),
    ]
