# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-07 00:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnairequalitatif', '0023_auto_20170106_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='inscrit_newsletter',
        ),
    ]
