# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnairequalitatif', '0025_auto_20170110_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('order', models.CharField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='qualitatif',
            name='quartier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnairequalitatif.Quartier', verbose_name='15. Quel est votre quartier de résidence?'),
        ),
    ]
