# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnairequalitatif', '0029_auto_20170110_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='quartier',
            name='order',
            field=models.CharField(default='1', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qualitatif',
            name='quartier',
            field=models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.CASCADE, to='questionnairequalitatif.Quartier', to_field='name', verbose_name='15. Quel est votre quartier de résidence?'),
        ),
    ]
