# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 23:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnairequalitatif', '0031_auto_20170110_1821'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quartier2',
            new_name='Quartier',
        ),
    ]
