# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 23:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnairequalitatif', '0033_auto_20170110_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualitatif',
            old_name='quartier',
            new_name='quartier_residence',
        ),
    ]
