# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 23:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnairequalitatif', '0034_auto_20170110_1848'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quartier',
            new_name='Quartierdb',
        ),
        migrations.RenameField(
            model_name='qualitatif',
            old_name='quartier_residence',
            new_name='quartier',
        ),
    ]
