# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnairequalitatif', '0035_auto_20170110_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quartierdb',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
