# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 04:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnairequalitatif', '0036_auto_20170110_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='VilleOrigine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=1000, unique=True)),
                ('order', models.CharField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='qualitatif',
            name='ville_origine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnairequalitatif.VilleOrigine', verbose_name='16. Où se trouve votre ville d’origine?'),
        ),
        migrations.AlterField(
            model_name='quartierdb',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
