# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 04:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnairequalitatif', '0038_auto_20170110_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceRevenus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=1000, unique=True)),
                ('order', models.CharField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='qualitatif',
            name='source_revenus',
            field=models.ForeignKey(default='Sélectionnez', on_delete=django.db.models.deletion.CASCADE, to='questionnairequalitatif.SourceRevenus', verbose_name='12. Quelle est votre source principale de revenu?'),
        ),
    ]
