# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 04:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnairequalitatif', '0039_auto_20170110_2357'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SourceRevenus',
            new_name='SourceRevenu',
        ),
    ]
