# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 05:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnairequalitatif', '0040_auto_20170110_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=1000, unique=True)),
                ('order', models.CharField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='qualitatif',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnairequalitatif.Genre', verbose_name='7. Votre genre :'),
        ),
    ]
