# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnairequalitatif', '0043_auto_20170111_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualitatif',
            name='enfant_0_a_4',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default='0', max_length=1, verbose_name='9. Nombre d’enfants participants avec vous:     - enfant(s) de 0-4 ans :'),
        ),
    ]
