# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 05:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnairequalitatif', '0044_auto_20170111_0026'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qualitatif',
            new_name='QuestionnaireQualitatif',
        ),
    ]
