# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-10 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnairequalitatif', '0045_auto_20170111_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairequalitatif',
            name='age',
            field=models.CharField(choices=[('MOINS_18', 'Moins de 18 ans'), ('18_24', '18-24'), ('25_34', '25-34'), ('35_50', '35-50'), ('50_64', '50-64'), ('65_ET_PLUS', '65 et plus')], default='25-34', max_length=100, verbose_name='8. Votre âge :'),
        ),
        migrations.AlterField(
            model_name='questionnairequalitatif',
            name='bien_etre',
            field=models.CharField(choices=[('PHYSIQUE', 'Physique'), ('MENTAL', 'Mental'), ('AUCUN', 'Ni l’un ni l’autre')], default='Aucun', max_length=50, verbose_name='3. Considérez-vous que cette activité à contribué à votre bien-être?'),
        ),
        migrations.AlterField(
            model_name='questionnairequalitatif',
            name='condition_physique_ou_cognitive',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non')], default='Oui', max_length=100, verbose_name='10. Avez-vous une condition physique ou cognitive particulière?'),
        ),
        migrations.AlterField(
            model_name='questionnairequalitatif',
            name='condition_physique_ou_cognitive_si_oui',
            field=models.CharField(blank=True, max_length=1000, verbose_name="Si 'Oui', quoi ?"),
        ),
        migrations.AlterField(
            model_name='questionnairequalitatif',
            name='envie_legumes',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non')], default='Oui', max_length=3, verbose_name='4. Est-ce que cette activité vous a donné envie de manger plus de fruits/légumes?'),
        ),
        migrations.AlterField(
            model_name='questionnairequalitatif',
            name='genre',
            field=models.ForeignKey(default='Femme', on_delete=django.db.models.deletion.CASCADE, to='questionnairequalitatif.Genre', verbose_name='7. Votre genre :'),
        ),
        migrations.AlterField(
            model_name='questionnairequalitatif',
            name='implication',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non')], default='Oui', max_length=3, verbose_name='6. Suite à cette activité, vous sentez-vous plus impliqué dans votre quartier?'),
        ),
        migrations.AlterField(
            model_name='questionnairequalitatif',
            name='langue',
            field=models.ForeignKey(default='Francais', on_delete=django.db.models.deletion.CASCADE, to='questionnairequalitatif.Langue', verbose_name='14. Quelle langue parlez vous le plus souvent à la maison?'),
        ),
        migrations.AlterField(
            model_name='questionnairequalitatif',
            name='lien',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non')], default='Oui', max_length=3, verbose_name='2. Lors de cette activité d’agriculture urbaine, avez-vous rencontré ou tissé des liens avec une nouvelle personne?'),
        ),
        migrations.AlterField(
            model_name='questionnairequalitatif',
            name='nouvelle_competence',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non')], default='Oui', max_length=100, verbose_name='5. Avez-vous appris quelque chose de nouveau et/ou développé de nouvelles compétences suite à cette activité?'),
        ),
        migrations.AlterField(
            model_name='questionnairequalitatif',
            name='nouvelle_competence_si_oui',
            field=models.CharField(blank=True, max_length=1000, verbose_name="Si 'Oui', quoi ?"),
        ),
        migrations.AlterField(
            model_name='questionnairequalitatif',
            name='quartier',
            field=models.ForeignKey(default='Ahuntsic-Cartierville', on_delete=django.db.models.deletion.CASCADE, to='questionnairequalitatif.Quartierdb', verbose_name='15. Quel est votre quartier de résidence?'),
        ),
        migrations.AlterField(
            model_name='questionnairequalitatif',
            name='raison',
            field=models.ManyToManyField(default='Par souci environnemental', to='questionnairequalitatif.Raison', verbose_name='1. Pour quelles raisons avez-vous participé à cette activité ?'),
        ),
        migrations.AlterField(
            model_name='questionnairequalitatif',
            name='resident_depuis',
            field=models.CharField(choices=[('PAS_RESIDENT', 'Je ne suis pas Résident'), ('MOINS_1_ANS', "Moins d'un an"), ('ENTRE_1_ET_2_ANS', 'Entre 1 et 2 ans'), ('PLUS_DE_2_ANS', 'Plus de 2 ans')], default='Je ne suis pas Résident', max_length=100, verbose_name='17. Si vous n’êtes pas originaire de Montréal, depuis combien de temps vous y résidez?'),
        ),
        migrations.AlterField(
            model_name='questionnairequalitatif',
            name='revenu_annuel_familial',
            field=models.CharField(choices=[('0_10K', '0 - 9 999$'), ('10K_20K', '10 000$ - 19 999$'), ('20K_30K', '20 000$ - 29 999$'), ('30K_40K', '30 000$ - 39 999$'), ('40K_50K', '40 000$ - 49 999$'), ('PLUS_DE_50K', 'Plus de 50 000$'), ('NE_REPOND_PAS', 'Je préfère ne pas répondre')], default='0 - 9 999$', max_length=100, verbose_name='13. Quel est le revenu annuel familial avant impôt ?'),
        ),
        migrations.AlterField(
            model_name='questionnairequalitatif',
            name='situation_familiale',
            field=models.CharField(choices=[('PERSONNE_SEULE', 'Personne seule'), ('COUPLE_SANS_ENFANT', 'Couple sans enfant'), ('COUPLE_AVEC_ENFANT', 'Couple avec enfant'), ('FAMILLE_MONO_PARENTALE', 'Famille mono-parentale')], default='Personne seule', max_length=100, verbose_name='11. Quelle est votre situation familiale ?'),
        ),
        migrations.AlterField(
            model_name='questionnairequalitatif',
            name='source_revenus',
            field=models.ForeignKey(default='Travail', on_delete=django.db.models.deletion.CASCADE, to='questionnairequalitatif.SourceRevenu', verbose_name='12. Quelle est votre source principale de revenu?'),
        ),
        migrations.AlterField(
            model_name='questionnairequalitatif',
            name='ville_origine',
            field=models.ForeignKey(default='Au Quebec', on_delete=django.db.models.deletion.CASCADE, to='questionnairequalitatif.VilleOrigine', verbose_name='16. Où se trouve votre ville d’origine?'),
        ),
    ]
