# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-10 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnairequalitatif', '0046_auto_20170210_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairequalitatif',
            name='raison',
            field=models.ManyToManyField(default='Par souci environnemental', help_text='plusieurs choix possibles', to='questionnairequalitatif.Raison', verbose_name='1. Pour quelles raisons avez-vous participé à cette activité ?'),
        ),
    ]
