# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-13 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnairequalitatif', '0047_auto_20170210_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairequalitatif',
            name='raison',
            field=models.ManyToManyField(default='Par souci environnemental', to='questionnairequalitatif.Raison', verbose_name='1. Pour quelles raisons avez-vous participé à cette activité ? (plusieurs choix possibles)'),
        ),
    ]
