# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnairequantitatif', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnairequantitatiffacultatif',
            name='city',
        ),
        migrations.AddField(
            model_name='questionnairequantitatiffacultatif',
            name='ca_agriculture_urbaine',
            field=models.IntegerField(default='0', help_text='ex format de réponse : 10000', verbose_name='Chiffre de ventes du marché pour les produits issus d’agriculture urbaine seulement, en dollars ($)'),
        ),
        migrations.AddField(
            model_name='questionnairequantitatiffacultatif',
            name='ca_semis',
            field=models.IntegerField(default='0', help_text='ex format de réponse : 3000', verbose_name='Chiffre de vente des plantules (semis) produits en dollars ($)'),
        ),
        migrations.AddField(
            model_name='questionnairequantitatiffacultatif',
            name='ca_total',
            field=models.IntegerField(default='0', help_text='ex format de réponse : 25000', verbose_name='Chiffre de ventes total du marché en dollars ($)'),
        ),
        migrations.AddField(
            model_name='questionnairequantitatiffacultatif',
            name='nombre_heures_aines',
            field=models.IntegerField(default='0', help_text='ex format de réponse : 100', verbose_name='Nombre d’heures d’activités organisées spécifiquement pour les personnes aînées'),
        ),
        migrations.AddField(
            model_name='questionnairequantitatiffacultatif',
            name='nombre_heures_enfant',
            field=models.IntegerField(default='0', help_text='ex format de réponse : 100', verbose_name='Nombre d’heures d’activités organisées spécifiquement pour les enfants'),
        ),
        migrations.AddField(
            model_name='questionnairequantitatiffacultatif',
            name='nombre_paniers',
            field=models.IntegerField(default='0', help_text='ex format de réponse : 50', verbose_name='Nombre de paniers de légumes vendus'),
        ),
        migrations.AddField(
            model_name='questionnairequantitatiffacultatif',
            name='nombre_ruches',
            field=models.IntegerField(default='0', help_text='ex format de réponse : 2', verbose_name='Nombre de ruches entretenues'),
        ),
        migrations.AddField(
            model_name='questionnairequantitatiffacultatif',
            name='nombre_semis_rustiques',
            field=models.IntegerField(default='0', help_text='ex format de réponse : 15', verbose_name='Nombre de variétés ancestrales/rustiques de plantules produits'),
        ),
        migrations.AddField(
            model_name='questionnairequantitatiffacultatif',
            name='nombre_sujets',
            field=models.IntegerField(default='0', help_text='par exemple une série d’ateliers peut porter sur : l’introduction à l’agriculture urbaine, la construction de bacs à double fond, l’introduction à la cuisine italienne – pour un total de 3 sujets abordés (ex format de réponse : 5)', verbose_name='Nombre de sujets différents abordés dans l’ensemble des ateliers organisés'),
        ),
        migrations.AddField(
            model_name='questionnairequantitatiffacultatif',
            name='poids_composte',
            field=models.IntegerField(default='0', help_text='ex format de réponse : 1000', verbose_name='Poids du composte produit dans l’ensemble des jardins en kg'),
        ),
        migrations.AddField(
            model_name='questionnairequantitatiffacultatif',
            name='poids_miel',
            field=models.IntegerField(default='0', help_text='ex format de réponse : 30', verbose_name='Quantité de miel produit en litres'),
        ),
        migrations.AddField(
            model_name='questionnairequantitatiffacultatif',
            name='poids_pluie',
            field=models.IntegerField(default='0', help_text='ex format de réponse : 1000', verbose_name='Quantité d’eau de pluie ramassée en litres'),
        ),
        migrations.AddField(
            model_name='questionnairequantitatiffacultatif',
            name='prix_panier',
            field=models.IntegerField(default='0', help_text='ex format de réponse : 20', verbose_name='Prix moyen de vente d’un panier de légumes en dollars ($)'),
        ),
        migrations.AddField(
            model_name='questionnairequantitatiffacultatif',
            name='semis',
            field=models.IntegerField(default='0', help_text='ex format de réponse : 1000', verbose_name='Nombre des plantules (semis) produits'),
        ),
    ]
