# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-08 02:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnairequantitatif', '0004_auto_20170111_0026'),
        ('questionnairequantitatif', '0002_auto_20170207_1858'),
    ]

    operations = [
    ]
