# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courriel', models.EmailField(blank=True, max_length=254, verbose_name='Courriel')),
                ('nom_referent', models.TextField(blank=True, verbose_name='Votre nom')),
                ('nom_organisme', models.TextField(blank=True, verbose_name='Nom Organisme')),
                ('mot_de_passe', models.CharField(max_length=20, verbose_name='Mot de passe')),
                ('mot_de_passe_conf', models.CharField(max_length=20, verbose_name='Confirmation du mot de passe')),
            ],
        ),
    ]
