# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-03 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewAccount',
        ),
    ]
