# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 20:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('order', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_organisme', models.TextField(blank=True)),
                ('nom_referent', models.TextField(blank=True)),
                ('courriel', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True)),
                ('mandat', models.TextField(blank=True)),
                ('objetif', models.TextField(blank=True)),
                ('personnes_impliquees', models.IntegerField(blank=True)),
                ('personnes_employees', models.IntegerField(blank=True)),
                ('personnes_moins_de_25', models.IntegerField(blank=True)),
                ('retombees', models.TextField(blank=True)),
                ('superficie', models.IntegerField(default='0')),
                ('adresse_jardin', models.TextField(blank=True)),
                ('city', models.CharField(default='Montreal', max_length=255)),
                ('location', location_field.models.plain.PlainLocationField(default='45.5016889,-73.56725599999999', max_length=63)),
                ('categories', models.ManyToManyField(default='Sélectionnez', to='profil.Categorie', verbose_name='8. Quelles sont les catégories d’activités mises sur pied par votre organisme?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
