# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='user',
            new_name='current_user',
        ),
    ]
