# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-13 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0003_auto_20170207_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='nom_organisme',
            field=models.TextField(blank=True, verbose_name='1. Nom de l’organisme :'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='nom_referent',
            field=models.TextField(blank=True, verbose_name="2. Nom des ou de la personne ressource qui s’impliquera dans le projet ' Récolter- Montréal ' pour la saison 2016:"),
        ),
    ]
